### ISSUE TITLE
unable to delete medication

### ISSUE THREAD

**Issue by dukemike** [interopion/cloudrx-issues#4]
Attempting to delete a medication displays a 404 error.

**Comment by vlad-ignatov** [comment]
Yes, this was still pointing to my local backend. It should be OK now.

**Comment by dukemike** [comment]
It seems like my dukemike account is no longer able to manage drugs, but I was able to change the NDC for Allegra (last page) to 13 before the page went read-only.

**Comment by vlad-ignatov** [comment]
That's very odd and difficult to reproduce. I think it might be a caching issue. Since this is a single page app, it's very important to ensure that the browser cache does not affect our code changes. I made it so that every js and css asset from our domain contains special build hash in it's file name or as GET param. This way everything can be cached but only until the next build. From now on we shouldn't worry about the cache but to be sure you are using the latest version you will have to do the following once:
1. Log out
2. Clear browser cache
3. Refresh
4. Log in
